export const incidents = [
  {
    id: 1,
    priority: "critical",
    name: "Keenan Ray",
    time: 45,
    location: "435 Nagel Street, College Station TX",
    phone: "555-218-3490",
    injuries: false,
    gas: false,
    fire: false,
    trapped: false,
    vehicles: "",
    isActive: true,
    latitude: 30.61614,
    longitude: -96.33887,
    notes: "",
    ready: false,
    dispatched: {
      ambulance: false,
      fire: false,
      police: false,
    },
    createdAt: null,
    dispatchedAt: null,
    triageScore: 0,
    emotionScore: "",
    transcript: "",
    generatedResponse: "",
  },
  {
    id: 2,
    priority: "critical",
    name: "Rolland James",
    time: 75,
    location: "402 Pine Ridge Dr, College Station TX",
    phone: "115-218-3390",
    injuries: false,
    gas: false,
    fire: false,
    ready: false,
    trapped: false,
    vehicles: "",
    isActive: true,
    latitude: 30.60775,
    longitude: -96.31549,
    notes: "",
    dispatched: {
      ambulance: false,
      fire: false,
      police: false,
    },
    createdAt: null,
    dispatchedAt: null,
    triageScore: 0,
    emotionScore: "",
    transcript: "",
    generatedResponse: "",
  },
  {
    id: 3,
    priority: "critical",
    name: "Alex Ross",
    time: 105,
    location: "1908 Texas Ave S, College Station TX",
    phone: "545-222-3490",
    injuries: false,
    gas: false,
    ready: false,
    fire: false,
    trapped: false,
    vehicles: "",
    isActive: true,
    latitude: 30.61342,
    longitude: -96.31758,
    notes: "",
    dispatched: {
      ambulance: false,
      fire: false,
      police: false,
    },
    createdAt: null,
    dispatchedAt: null,
    triageScore: 0,
    emotionScore: "",
    transcript: "",
    generatedResponse: "",
  },
  {
    id: 4,
    priority: "critical",
    name: "Marcus Williamson",
    time: 105,
    location: "402 Pine Ridge Drive, College Station TX",
    phone: "545-222-3490",
    injuries: false,
    gas: false,
    ready: false,
    fire: false,
    trapped: false,
    vehicles: "",
    isActive: true,
    latitude: 30.61342,
    longitude: -96.31758,
    notes: "",
    dispatched: {
      ambulance: false,
      fire: false,
      police: false,
    },
    createdAt: null,
    dispatchedAt: null,
    triageScore: 0,
    emotionScore: "",
    transcript: "",
    generatedResponse: "",
  },
];
